### ISSUE TITLE
Project overall

### ISSUE THREAD

**Issue by makeworld-the-better-one** [muka/peerjs-go#1]
Thanks so much for creating this project! It looks very useful and I'm excited to try it out. I had some questions about the project overall.

- Is the project working between Go peers right now? If not, what is missing?
- What can I do to help? What is left to work on?
- Do you have any other suggestions for p2p communication in Go, if not this library?

Thanks!

**Comment by muka** [comment]
Hi,
Yes go and js can exchange messages but serialization has to be set to raw(peerjs uses a binary pack serialization that is not implemented in go). Not tried yet with the python version but should not be an issue.

Both server and client should be pretty aligned to peerjs. The challenge is to keep it up to date and compatible. I was also considering to add pion stun server to the server implementation.
VIdeo streaming testing is pretty limited and in general we miss examples.
If you see room for improvement feel free to send a PR!

I have tried with go-libp2p but depends on your requirements and time available

Thank

**Comment by makeworld-the-better-one** [comment]
Great to hear it's all working! Thanks for creating this, it's very useful.

> I was also considering to add pion stun server to the server implementation.

I wouldn't do this I think. It's nice to keep them separate, and keep the signaling server very simple. There are many free STUN servers available, and if someone wants to run their own it's not hard to do separately.

> If you see room for improvement feel free to send a PR!

I've already made a couple, and look forward to making more :smile:

**Comment by golimix** [comment]
Hi,

has plan to support the binary serialization ?

> Hi, Yes go and js can exchange messages but serialization has to be set to raw(peerjs uses a binary pack serialization that is not implemented in go). Not tried yet with the python version but should not be an issue.
> 
> Both server and client should be pretty aligned to peerjs. The challenge is to keep it up to date and compatible. I was also considering to add pion stun server to the server implementation. VIdeo streaming testing is pretty limited and in general we miss examples. If you see room for improvement feel free to send a PR!
> 
> I have tried with go-libp2p but depends on your requirements and time available
> 
> Thank

**Comment by muka** [comment]
Hi the project is not actively developed, however it's open for contributions in case you want to provide a PR for this. Thanks!
