### ISSUE TITLE
websocket: bad handshake

### ISSUE THREAD

**Issue by fanhai** [muka/peerjs-go#16]
time="2022-12-13T21:34:27+08:00" level=debug msg="Initializing id=peer1" module=peer source="peer:peer1"
time="2022-12-13T21:35:53+08:00" level=debug msg="Connecting to ws://127.0.0.1:9000/myapp/peerjs?key=peerjs&id=peer1&token=IURA5ZPod9B" module=peer source=socket
panic: websocket: bad handshake

goroutine 1 [running]:
main.fail({0x95f200, 0xc000178300})
	c:/Users/fanhai/go/src/github.com/muka/peerjs-go/_examples/simple/main.go:12 +0x65
main.main()
	c:/Users/fanhai/go/src/github.com/muka/peerjs-go/_examples/simple/main.go:29 +0x165

我先运行 cmd/server.go
在运行 simple 报这个错误是什么情况呀？

**Comment by muka** [comment]
Sorry, can not help without additional details. Please reopen when you have more information
