### ISSUE TITLE
Support TURN server

### ISSUE THREAD

**Issue by makeworld-the-better-one** [muka/peerjs-go#2]
The peerjs library supports using TURN servers, and has one built-in.

https://github.com/peers/peerjs/blob/cfc37c7988d8ef3d2c1d7b6123562dd2af59defc/lib/util.ts#L8

It'd be nice if this library could have that default. I believe it can currently be specified by the user manually through `Options.Configuration`.

**Comment by muka** [comment]
Yes good point, do you want to provide a PR for it? Thanks

**Comment by makeworld-the-better-one** [comment]
Added it in #4. I've created another PR in #3 by the way.
