### ISSUE TITLE
Depart from original API to make more idiomatic

### ISSUE THREAD

**Issue by makeworld-the-better-one** [muka/peerjs-go#6]
Currently this library's API mirrors the PeerJS one. This is usable, but not very idiomatic for Go, using things like emitters, etc. I have several ideas for how to improve and change the library so it's much easier and more familiar to Go programmers.

All the functionality would be the same, but I would get rid of emitters. I was also planning on adding a better API for raw data, where you just get an `io.ReadWriteCloser` with a peer, that does chunking automatically. This would make peerjs-go really easy to use as a generic data transport. I've already know of some code I can base this off of.

This would change a lot of stuff in the library, but would be worth it to improve usability. Is that okay with you? I don't have this PR ready, but I'd like to know what you think before I start working on it.

**Comment by makeworld-the-better-one** [comment]
The chunking/buffering I'm picturing would only be for raw transport, it wouldn't be compatible with the chunking/buffering done in the PeerJS API. But it would still be very useful.

**Comment by muka** [comment]
I am all in with your initiative!  I admit to have just converted peerjs to go without much attention to idiomatic go. Event emitter with interface {} argument, is objectively terrible :)

I'll review the PR or share your improvement plan so we can share the effort

**Comment by makeworld-the-better-one** [comment]
Glad to hear it! Here's what I'm thinking. I'm happy to implement this myself, but if you end up adding any of it, please mention it in this thread.

- Replace enum strings with custom types based on string, and remove the enum package
- Replace emitters with function types that can be placed in the configuration struct
	- Ideally there would be one func for `ConnectionEvent`, one for `PeerEvent`, and one for `PeerError`
	- But different types are returned for those even types, like `string` for IDs, and `*DataConnection` when connections are made
	- To avoid usage of `interface{}`, refactoring should happen so that the funcs only deal with known types
	- I'll have to think of how to do that
- Add function that can take a `*DataConnection` and return an `io.ReadWriteCloser`, as I mentioned in the original comment
	- I'll model the function off of [this code](https://github.com/saljam/webwormhole/blob/1c8919c7052042858e8ccf484f058be480affdd3/wormhole/dial.go) that does the same thing
	- Max chunk size will be 32 KiB, as used by [this code](https://github.com/saljam/webwormhole/blob/1c8919c7052042858e8ccf484f058be480affdd3/cmd/ww/file.go#L15)
	- Would require `Reliable` to be true and should return an error or panic if it's not
	- Using this function would disable any funcs that recieve data from running

**Comment by muka** [comment]
Wow those would be great progresses! Happy to test them out when you have them ready.

**Comment by makeworld-the-better-one** [comment]
Sounds good!

Btw I've created another PR, #5. It's okay to create PRs without issues, right?

**Comment by muka** [comment]
Yes it's ok, happy to review them

**Comment by makeworld-the-better-one** [comment]
I still intend on doing this, although I don't have the time to work on it right now. If I end up deciding to abandon this I will let you know.

**Comment by muka** [comment]
Thank you for the commitment, feel free to close anytime. We can start over
in the future
