### ISSUE TITLE
Compile to WASM

### ISSUE THREAD

**Issue by makeworld-the-better-one** [muka/peerjs-go#7]
It'd be useful to be able to compile this to WASM and use it in the browser. Obviously for a browser-native project you'd use the actual PeerJS library, but when using this library as part of a larger project, it's useful to only need one codebase. For example the webrtc package will call the JS webrtc functions when compiled to WASM.

The only dependency I know of that blocks this is [gorilla/websocket](https://github.com/gorilla/websocket). That one can be replaced by [nhooyr/websocket](https://github.com/nhooyr/websocket).

Are there other parts of the library that might have problems with WASM?

**Comment by muka** [comment]
Personally I do not have experience with WASM. I think the websocket part is not particularly complex to be replaced. Do you plan to port it ?

**Comment by makeworld-the-better-one** [comment]
gorilla/websocket can't compile to WASM, but nhooyr/websocket can. By switching out the dependencies the library should be able to compile to WASM. It's not that the websocket is too complex, or that I want to personally port anything.

**Comment by muka** [comment]
Ok maybe I expressed poorly on my side, I meant it seems a good idea!

**Comment by makeworld-the-better-one** [comment]
Oh ok, sounds good! I can do this at some point, I'll make a PR.
