### ISSUE TITLE
Undefined variable in util.go

### ISSUE THREAD

**Issue by o-k-a-y** [muka/peerjs-go#9]
Hopefully it's not because I'm not familiar with how go works, but when running:

../../../go/pkg/mod/github.com/muka/peerjs-go@v0.0.0-20210427075427-c4a7fe257084/util/util.go:45:41: undefined: ChunkedMTU
../../../go/pkg/mod/github.com/muka/peerjs-go@v0.0.0-20210427075427-c4a7fe257084/util/util.go:50:49: undefined: ChunkedMTU

Is there some step I'm missing? Thank you.

**Comment by muka** [comment]
Sorry for the late response, @brimstone fixed it! Thanks
